/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpuid_CPUIDJNIWrapper */

#ifndef _Included_cpuid_CPUIDJNIWrapper
#define _Included_cpuid_CPUIDJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpuid_CPUIDJNIWrapper
 * Method:    getCPUID
 * Signature: ()I
 */
JNIEXPORT jintArray JNICALL Java_cpuid_CPUIDJNIWrapper_getCPUID
  (JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_cpuid_CPUIDJNIWrapper_getMaxCPUID
  (JNIEnv *, jclass, jint, jint);
  
#ifdef __cplusplus
}
#endif
#endif
